version: '2'

services:
  db:
    container_name: gwapit-test-db
    image: postgres
  core:
    container_name: gwapit-test-core
    build: ./core
    command: bash -c "./manage.py migrate; ./manage.py loaddata fighters; while :; do ./manage.py runserver 0.0.0.0:9081  --settings=gwapit.settings; sleep 1; done"

    volumes:
      - ./core:/opt/gwapit
    ports:
      - "9081:9081"
    depends_on:
      - db
  web:
    container_name: gwapit-test-web
    build: ./web
    command: serve --host 0.0.0.0 --port 9080
    volumes:
      - ./web:/opt/gwapit
    ports:
      - "9080:9080"